/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as WSlugIndexRouteImport } from './routes/w.$slug.index'
import { Route as WSlugBoardRouteImport } from './routes/w.$slug.board'
import { Route as WSlugEpicsRouteImport } from './routes/w.$slug.epics'
import { Route as WSlugGraphRouteImport } from './routes/w.$slug.graph'
import { Route as WSlugIssueIdRouteImport } from './routes/w.$slug_.issue.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugIndexRoute = WSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugBoardRoute = WSlugBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugEpicsRoute = WSlugEpicsRouteImport.update({
  id: '/epics',
  path: '/epics',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugGraphRoute = WSlugGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => WSlugRoute,
} as any)
const WSlugIssueIdRoute = WSlugIssueIdRouteImport.update({
  id: '/w/$slug_/issue/$id',
  path: '/w/$slug/issue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/board': typeof WSlugBoardRoute
  '/w/$slug/epics': typeof WSlugEpicsRoute
  '/w/$slug/graph': typeof WSlugGraphRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug/issue/$id': typeof WSlugIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$slug/board': typeof WSlugBoardRoute
  '/w/$slug/epics': typeof WSlugEpicsRoute
  '/w/$slug/graph': typeof WSlugGraphRoute
  '/w/$slug': typeof WSlugIndexRoute
  '/w/$slug/issue/$id': typeof WSlugIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$slug': typeof WSlugRouteWithChildren
  '/w/$slug/board': typeof WSlugBoardRoute
  '/w/$slug/epics': typeof WSlugEpicsRoute
  '/w/$slug/graph': typeof WSlugGraphRoute
  '/w/$slug/': typeof WSlugIndexRoute
  '/w/$slug_/issue/$id': typeof WSlugIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$slug'
    | '/w/$slug/board'
    | '/w/$slug/epics'
    | '/w/$slug/graph'
    | '/w/$slug/'
    | '/w/$slug/issue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w/$slug/board'
    | '/w/$slug/epics'
    | '/w/$slug/graph'
    | '/w/$slug'
    | '/w/$slug/issue/$id'
  id:
    | '__root__'
    | '/'
    | '/w/$slug'
    | '/w/$slug/board'
    | '/w/$slug/epics'
    | '/w/$slug/graph'
    | '/w/$slug/'
    | '/w/$slug_/issue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WSlugRoute: typeof WSlugRouteWithChildren
  WSlugIssueIdRoute: typeof WSlugIssueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug/': {
      id: '/w/$slug/'
      path: '/'
      fullPath: '/w/$slug/'
      preLoaderRoute: typeof WSlugIndexRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/board': {
      id: '/w/$slug/board'
      path: '/board'
      fullPath: '/w/$slug/board'
      preLoaderRoute: typeof WSlugBoardRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/epics': {
      id: '/w/$slug/epics'
      path: '/epics'
      fullPath: '/w/$slug/epics'
      preLoaderRoute: typeof WSlugEpicsRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug/graph': {
      id: '/w/$slug/graph'
      path: '/graph'
      fullPath: '/w/$slug/graph'
      preLoaderRoute: typeof WSlugGraphRouteImport
      parentRoute: typeof WSlugRoute
    }
    '/w/$slug_/issue/$id': {
      id: '/w/$slug_/issue/$id'
      path: '/w/$slug/issue/$id'
      fullPath: '/w/$slug/issue/$id'
      preLoaderRoute: typeof WSlugIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WSlugRouteChildren {
  WSlugBoardRoute: typeof WSlugBoardRoute
  WSlugEpicsRoute: typeof WSlugEpicsRoute
  WSlugGraphRoute: typeof WSlugGraphRoute
  WSlugIndexRoute: typeof WSlugIndexRoute
}

const WSlugRouteChildren: WSlugRouteChildren = {
  WSlugBoardRoute: WSlugBoardRoute,
  WSlugEpicsRoute: WSlugEpicsRoute,
  WSlugGraphRoute: WSlugGraphRoute,
  WSlugIndexRoute: WSlugIndexRoute,
}

const WSlugRouteWithChildren = WSlugRoute._addFileChildren(WSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WSlugRoute: WSlugRouteWithChildren,
  WSlugIssueIdRoute: WSlugIssueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
